// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtccPH4E8tmJ4O5Q-UiqdhHAXGb7oL7oM',
    appId: '1:795301525713:web:2b85d3fac27dddd643adf0',
    messagingSenderId: '795301525713',
    projectId: 'food-app-b818b',
    authDomain: 'food-app-b818b.firebaseapp.com',
    storageBucket: 'food-app-b818b.appspot.com',
    measurementId: 'G-0EGX04HSNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHvs_YDC4qwP3Mi0St_ZPRZyr46KOkcK8',
    appId: '1:795301525713:android:3aaaff1860801e9e43adf0',
    messagingSenderId: '795301525713',
    projectId: 'food-app-b818b',
    storageBucket: 'food-app-b818b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE_-sFRzYPVFVIwQQPbRCBmH6GSUfmFgc',
    appId: '1:795301525713:ios:ed4bc556c47efa3043adf0',
    messagingSenderId: '795301525713',
    projectId: 'food-app-b818b',
    storageBucket: 'food-app-b818b.appspot.com',
    iosClientId: '795301525713-fic9fakehb04tqu1pjcs88fb3nreurtu.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE_-sFRzYPVFVIwQQPbRCBmH6GSUfmFgc',
    appId: '1:795301525713:ios:add0c2018390255c43adf0',
    messagingSenderId: '795301525713',
    projectId: 'food-app-b818b',
    storageBucket: 'food-app-b818b.appspot.com',
    iosClientId: '795301525713-gdf3qgdc2aseffcpcb82ql89i1fd408f.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp.RunnerTests',
  );
}
